//! v0.5: interop with the `.ffs-sync` marker of the CodeSync ecosystem.
//! Marker semantics (see the win-mac sync architecture): a directory containing a `.ffs-sync` file = a sync territory.
//! - find_territories: scan for markers, emit territory paths relative to the root
//! - gen_jobs: generate one syncdash job per territory (cs-<slug>.toml, sync mode by default + an automatic archive path),
//!   same origin and same meaning as FFS's Update-CodeSyncConfig.ps1 — CodeSync, the syncdash edition.
//! Generation is idempotent: a re-run overwrites cs-*.toml (same spirit as the FFS generator); hand-written jobs are untouched.

use crate::job::Job;
use std::path::{Path, PathBuf};

const MARKER: &str = ".ffs-sync";
const PRUNE_DIRS: &[&str] = &[
    ".git", "node_modules", "target", "build", "dist", "__pycache__", ".venv", "venv",
    "worktrees", ".syncdash", "$RECYCLE.BIN", "System Volume Information",
];

/// Returns the directories holding a .ffs-sync marker (relative to root, '/'-separated, sorted)
pub fn find_territories(root: &Path) -> Vec<String> {
    let mut out = Vec::new();
    let walker = walkdir::WalkDir::new(root)
        .follow_links(false)
        .max_depth(7)
        .into_iter()
        .filter_entry(|e| {
            if e.depth() == 0 || !e.file_type().is_dir() {
                return true;
            }
            let name = e.file_name().to_string_lossy();
            !PRUNE_DIRS.iter().any(|d| d.eq_ignore_ascii_case(&name))
        });
    for item in walker.flatten() {
        if item.file_type().is_file() && item.file_name().to_string_lossy() == MARKER {
            if let Some(dir) = item.path().parent() {
                if let Ok(rel) = dir.strip_prefix(root) {
                    out.push(rel.to_string_lossy().replace('\\', "/"));
                }
            }
        }
    }
    out.sort();
    out.dedup();
    out
}

fn slug(rel: &str) -> String {
    let mut s: String = rel
        .to_lowercase()
        .chars()
        .map(|c| if c == '/' || c == '\\' || c == ' ' || c == '.' { '-' } else { c })
        .collect();
    while s.contains("--") {
        s = s.replace("--", "-");
    }
    s.trim_matches('-').to_string()
}

fn archive_dir() -> PathBuf {
    crate::foundation::dirs::archive_dir()
}

fn to_native(rel: &str) -> String {
    if cfg!(windows) { rel.replace('/', "\\") } else { rel.to_string() }
}

pub struct GenOutcome {
    pub name: String,
    pub territory: String,
    pub path: PathBuf,
}

/// Remote pipeline generation parameters (enabled by --remote-host)
pub struct RemoteGen {
    pub host: String,
    pub root_base: String,
    pub exe: Option<String>,
}

/// Generate one `cs-<slug>.toml` job per territory. Target-side path = target_root + the same relative path.
pub fn gen_jobs(source_root: &Path, target_root: &Path, mode: &str, rigor: &str, remote: Option<&RemoteGen>) -> std::io::Result<Vec<GenOutcome>> {
    let terrs = find_territories(source_root);
    let jobs_dir = crate::foundation::dirs::jobs_dir();
    std::fs::create_dir_all(&jobs_dir)?;
    std::fs::create_dir_all(archive_dir())?;
    let mut out = Vec::new();
    for rel in terrs {
        let name = format!("cs-{}", slug(&rel));
        let native = to_native(&rel);
        let job = Job {
            mode: mode.to_string(),
            source: source_root.join(&native),
            // target_root may be UNC or posix — join each side with its own separator
            target: if target_root.to_string_lossy().contains('/') && !target_root.to_string_lossy().contains('\\') {
                PathBuf::from(format!("{}/{}", target_root.to_string_lossy().trim_end_matches('/'), rel))
            } else {
                target_root.join(&native)
            },
            archive: if mode == "sync" { Some(archive_dir().join(format!("{name}.jsonl"))) } else { None },
            include: Vec::new(),
            exclude: Vec::new(),
            no_hash: false,
            rigor: rigor.to_string(),
            case_sensitive: false,
            symlinks: "exclude".into(),
            versioning: false,
            // Code territory: dev-artifact excludes are explicitly on — code travels via git, so .git/node_modules stay out of file sync
            dev_excludes: true,
            remote_host: remote.map(|r| r.host.clone()),
            remote_root: remote.map(|r| format!("{}/{}", r.root_base.trim_end_matches('/'), rel)),
            remote_exe: remote.and_then(|r| r.exe.clone()),
            ..Default::default()
        };
        let toml_text = toml::to_string_pretty(&job)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, format!("toml serialize: {e}")))?;
        let path = jobs_dir.join(format!("{name}.toml"));
        std::fs::write(&path, format!("# generated by `syncdash gen-jobs` from .ffs-sync marker: {rel}\n# regenerate any time; edits here will be overwritten\n{toml_text}"))?;
        out.push(GenOutcome { name, territory: rel, path });
    }
    Ok(out)
}
