//! v0.5：与 CodeSync 生态的 `.ffs-sync` 标记打通。
//! 标记语义（见 win-mac 同步架构）：含 `.ffs-sync` 文件的目录 = 同步领地。
//! - find_territories：扫描标记，输出领地相对路径
//! - gen_jobs：每个领地生成一个 syncdash job（cs-<slug>.toml，默认 sync 模式 + 自动 archive 路径），
//!   与 FFS 的 Update-CodeSyncConfig.ps1 同源同义 —— syncdash 版的 CodeSync。
//! 生成是幂等的：重跑会覆盖 cs-*.toml（与 FFS 生成器同精神）；手工任务不受影响。

use crate::config::Job;
use std::path::{Path, PathBuf};

const MARKER: &str = ".ffs-sync";
const PRUNE_DIRS: &[&str] = &[
    ".git", "node_modules", "target", "build", "dist", "__pycache__", ".venv", "venv",
    "worktrees", ".syncdash", "$RECYCLE.BIN", "System Volume Information",
];

/// 返回含 .ffs-sync 标记的目录（相对 root，'/' 分隔，排序）
pub fn find_territories(root: &Path) -> Vec<String> {
    let mut out = Vec::new();
    let walker = walkdir::WalkDir::new(root)
        .follow_links(false)
        .max_depth(7)
        .into_iter()
        .filter_entry(|e| {
            if e.depth() == 0 || !e.file_type().is_dir() {
                return true;
            }
            let name = e.file_name().to_string_lossy();
            !PRUNE_DIRS.iter().any(|d| d.eq_ignore_ascii_case(&name))
        });
    for item in walker.flatten() {
        if item.file_type().is_file() && item.file_name().to_string_lossy() == MARKER {
            if let Some(dir) = item.path().parent() {
                if let Ok(rel) = dir.strip_prefix(root) {
                    out.push(rel.to_string_lossy().replace('\\', "/"));
                }
            }
        }
    }
    out.sort();
    out.dedup();
    out
}

fn slug(rel: &str) -> String {
    let mut s: String = rel
        .to_lowercase()
        .chars()
        .map(|c| if c == '/' || c == '\\' || c == ' ' || c == '.' { '-' } else { c })
        .collect();
    while s.contains("--") {
        s = s.replace("--", "-");
    }
    s.trim_matches('-').to_string()
}

fn archive_dir() -> PathBuf {
    crate::config::jobs_dir().parent().map(|p| p.join("archive")).unwrap_or_else(|| PathBuf::from("archive"))
}

fn to_native(rel: &str) -> String {
    if cfg!(windows) { rel.replace('/', "\\") } else { rel.to_string() }
}

pub struct GenOutcome {
    pub name: String,
    pub territory: String,
    pub path: PathBuf,
}

/// 远程管线生成参数（--remote-host 时启用）
pub struct RemoteGen {
    pub host: String,
    pub root_base: String,
    pub exe: Option<String>,
}

/// 为每个领地生成 `cs-<slug>.toml` job。target 侧路径 = target_root + 同一相对路径。
pub fn gen_jobs(source_root: &Path, target_root: &Path, mode: &str, rigor: &str, remote: Option<&RemoteGen>) -> std::io::Result<Vec<GenOutcome>> {
    let terrs = find_territories(source_root);
    let jobs_dir = crate::config::jobs_dir();
    std::fs::create_dir_all(&jobs_dir)?;
    std::fs::create_dir_all(archive_dir())?;
    let mut out = Vec::new();
    for rel in terrs {
        let name = format!("cs-{}", slug(&rel));
        let native = to_native(&rel);
        let job = Job {
            mode: mode.to_string(),
            source: source_root.join(&native),
            // target_root 可能是 UNC / posix，两边都按其自身分隔符拼
            target: if target_root.to_string_lossy().contains('/') && !target_root.to_string_lossy().contains('\\') {
                PathBuf::from(format!("{}/{}", target_root.to_string_lossy().trim_end_matches('/'), rel))
            } else {
                target_root.join(&native)
            },
            archive: if mode == "sync" { Some(archive_dir().join(format!("{name}.jsonl"))) } else { None },
            include: Vec::new(),
            exclude: Vec::new(),
            no_hash: false,
            rigor: rigor.to_string(),
            case_sensitive: false,
            symlinks: "exclude".into(),
            remote_host: remote.map(|r| r.host.clone()),
            remote_root: remote.map(|r| format!("{}/{}", r.root_base.trim_end_matches('/'), rel)),
            remote_exe: remote.and_then(|r| r.exe.clone()),
        };
        let toml_text = toml::to_string_pretty(&job)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, format!("toml serialize: {e}")))?;
        let path = jobs_dir.join(format!("{name}.toml"));
        std::fs::write(&path, format!("# generated by `syncdash gen-jobs` from .ffs-sync marker: {rel}\n# regenerate any time; edits here will be overwritten\n{toml_text}"))?;
        out.push(GenOutcome { name, territory: rel, path });
    }
    Ok(out)
}
